name: Rust Security Audit
on:
  pull_request:
    types:
      - opened
      - edited
      - reopned
      - synchronize
      - labeled
      - unlabeled
    paths:
      - '**/src/agent/Cargo.toml'
      - '**/src/agent/Cargo.lock'
      - '**/src/trace-forwarder/Cargo.toml'
      - '**/src/trace-forwarder/Cargo.lock'
      - '**/tools/agent-ctl/Cargo.toml'
      - '**/tools/agent-ctl/Cargo.lock'

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: move to the appropriate dir
        run : |
          pushd src/agent/
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
